### ISSUE TITLE
Attempt to release signatures for OpenUI5 1.60 Version

### ISSUE THREAD

**Issue by bd82** [SAP/ui5-typescript#1]

**Comment by bd82** [comment]
The generation of the signatures fails with syntax errors.
Some patches may need to be done directly to the OpenUI5 1.60 branch.

**Comment by Mischa1610** [comment]
It would be really good to have typings for older UI5 Versions than 1.64 (for example 1.60).
Is currently the plan to get it done for 1.60 and than also do more older versions or will it only be done for versions upwards 1.64?

**Comment by bd82** [comment]
I would likely try to release signatures for 1.60 next week.

Regarding releasing signatures for all the [release tracks of OpenUI5](https://openui5.org/releases/).
That is less likely to happen in the immediate future due to time constraints.
However if I succeed in implementing #22 it **may** be possible to integrate the d.ts generation into
the OpenUI5 builds instead of as a "satellite" project.

If that would/could be accomplished then the TypeScript signatures could become a "native" artifact of the OpenUI5 npm packages and always be "in sync".

That is my long term goal, but only time will tell if it can/would be accomplished...

**Comment by Mischa1610** [comment]
@bd82 that sounds really good, especially the idea in #22 it would definitely be the best solution to have the typings as part of the package (if the typings property in the package.json is set TypeScript would automatically know/use the definitions).

I will check for 1.60 the next weeks, thank you for the information.

**Comment by bd82** [comment]
https://www.npmjs.com/package/@openui5/ts-types/v/1.60.0
