### ISSUE TITLE
Complex JSDocs Types Parsing

### ISSUE THREAD

**Issue by bd82** [SAP/ui5-typescript#10]
We are only using a very naive parsing of the complex JSDocs types (e.g union types).
We probably need to use A JSDoc parser such as Doctorine and transform the result
to our own AST.

**Comment by lmcarreiro** [comment]
Why don't you use the api in json format available in the docs?

Link: https://sapui5.hana.ondemand.com/1.64.0/test-resources/sap/m/designtime/api.json

![image](https://user-images.githubusercontent.com/13019179/56976322-1627c300-6b49-11e9-9101-49dd12a911d1.png)

**Comment by bd82** [comment]
I am not sure I understand fully.

This project is already using the api.json as the inputs to generate the TypeScript signatures.
However some types in those JSDocs may use some of the more complex
JSDocs type annotations syntax: http://usejsdoc.org/tags-type.html
Which may not be properly understood during the conversion process.

**Comment by lmcarreiro** [comment]
I think I understood wrong. Disregard my comment...

**Comment by bd82** [comment]
Closing for tasks cleanup, may be re-opened / created as we discuss on future tasks for this project.
