### ISSUE TITLE
Create Demo with UI5 + TypeScript Babel Plugin

### ISSUE THREAD

**Issue by bd82** [SAP/ui5-typescript#116]

**Comment by dfenerski** [comment]
If not a demo, are there at least some docs or starting steps to get going with ts ui5?

**Comment by htammen** [comment]
Hi @dfenerski, 
I did not use UI5 tooling but in the meantime I realized some UI5 projects with Typescript leveraging this repostiroy output.
For details have a look at https://github.com/htammen/ui5con_typescript and https://github.com/htammen/ui5con_typescript/tree/master/presi.

Or have a look at my UI5Con presentation from Feb. 2020 in Bruxelles: https://www.youtube.com/watch?v=Ww_w9MoOEkM&list=PLVf0R17F93RXT2tzhHzAr-iiYTmc9KngS&index=6&t=0s

**Comment by bd82** [comment]
There are a couple of very tiny examples here (just for content assist / validation) scenarios.
- https://github.com/SAP/ui5-typescript/tree/master/demos

@codeworrior @petermuessig do you have any other more in-depth docs?

**Comment by dfenerski** [comment]
Hello @htammen, shortly after I wrote here, I found and watched your presentation at the ui5con(unrelated to your reply). It is great, it inspired me to write me next ui5 app in ts, because a working sample project was all I was looking for! Hereby I apply pressure to the team to release full support for ts :) Best Regards

**Comment by htammen** [comment]
Hi @dfenerski,
I talked several times to different people of the UI5 team about TS support. To name a few Peter Muessig, Stefan Beck, Margot Wollny. But it's always good that they see the demand from other people as well.
I think that this needs to be fully supported quickly because more and more frameworks and runtime environments switch to typescript (React, Angular, Vue, Deno).

**Comment by petermuessig** [comment]
Hi @htammen ,

we are still committed to provide the TypeScript support for UI5. We know the demand from the community and we now also have a proper staffing herefore. I will try to keep you in the loop.

Stay healthy! 

Cheers, 
Peter

**Comment by tony** [comment]
Excited about this!

To help set expectations correctly, will typings for UI5 be simple as `@types/react`, `@types/node`?

Seems like a hard thing to do! But that kind of integration would be excellent!

**Comment by htammen** [comment]
Hi Toni,
I think this already works if you don't leave the JS world. See here for details https://github.com/SAP/ui5-typescript

**Comment by bd82** [comment]
Hello @tony 

The types signatures are on npmjs.com and you can inspect some naive usage examples here:
- https://github.com/SAP/ui5-typescript/tree/master/demos

However the general problem is more complex and includes things such as:
- modernization of UI5 custom syntax/semantics (ES6 classes ES6 import/export).
- How to support type signatures for 3rd party libraries (not just UI5 "built-in" libs).

**Comment by tony** [comment]
@bd82  @htammen Thank you!

It will be interesting to see what happens with the typings!  

Regarding the example as we have it now, I'm wondering what these typings would look like on a react, vue, and/or angular project? I'm not quite sure what the examples are doing (e.g. `sap.ui.define`) and what it'd look like to integrate it into a project.

I think if there was an example of the typings with bundled vanilla typescript, angular, react, and vue, it'd be valuable!

**Comment by htammen** [comment]
@tony OpenUI5/SAPUI5 are competitives to React, Angular and Vue. So I don't understand what type of example you want to see with those frameworks.
You also don't combine a Vue application with React or Angular, do you?
You can integrate UI5 Webcomponents into React or Vue but that's another story.

**Comment by petermuessig** [comment]
The material how to get started with TypeScript and UI5 is collected at the GH page of this repository: https://sap.github.io/ui5-typescript/
