### ISSUE TITLE
About others incorrectly documented info in the official docs

### ISSUE THREAD

**Issue by lmcarreiro** [SAP/ui5-typescript#12]
I don't work with UI5 projects anymore, but I had a UI5 .d.ts generator once when openui5 was at version 1.48. I don't know how the docs are today, but I have some idea of the size of the trouble that you have here...

There are a lot of incorrectly documented details in the docs, and two ways to deal with these mistakes:
1. Fix the docs in the official repo
2. Setup the generator to workaround it

The first option is the best, but if you have to use the second, I have a list in my generator of the errors that I had to workaround when I was using my generator:
- [Types used in the docs that needed to be replaced in both places (return types and method parameter types): lines 31 to 65](https://github.com/lmcarreiro/ui5ts/blob/master/src/generator/config.json#L31)
- [Types declared in the docs as namespaces that needed to be generated as enum or classes: lines 70 to 83](https://github.com/lmcarreiro/ui5ts/blob/master/src/generator/config.json#L70)
- [Method parameter types: lines 87 to 92](https://github.com/lmcarreiro/ui5ts/blob/master/src/generator/config.json#L87)
- [Method return types: lines 96 to 114](https://github.com/lmcarreiro/ui5ts/blob/master/src/generator/config.json#L96)
- [Method that were overridden in inherited classes that were not compatible with the definition in the base classes: lines 122 to 138](https://github.com/lmcarreiro/ui5ts/blob/master/src/generator/config.json#L122)

This last type of error was the hardest one to deal with, I had to generate a method overload option like `(...args: any[]) => any` in the derived type to avoid compiler erros.

I don't have time to contribute to this project because I'm not working with UI5 anymore, but if you want to take a look at my previous work on this same subject, these are my repos:

Definitions in `.d.ts`:
- https://github.com/lmcarreiro/ui5-typescript-definitions/blob/master/1.48/sap.d.ts
- https://github.com/lmcarreiro/ui5-typescript-definitions/blob/master/1.48/jQuery.d.ts

Generator used to generate the `.d.ts` definitions: https://github.com/lmcarreiro/ui5ts/tree/master/src/generator

npm package to use at runtime: https://github.com/lmcarreiro/ui5ts
example project using it: https://github.com/lmcarreiro/ui5-typescript-example

**Comment by bd82** [comment]
Thanks for the information @lmcarreiro 

You will find many of the same kind of fixes here:
- https://github.com/SAP/ui5-typescript/tree/master/packages/dts-generator/lib/directives

I would like to extract these directives from the d.ts generator so they could be provided 
as arguments so this generator would not be coupled to OpenUI5 and could be used by other UI5 libraries as well.

My general approach is to focus on fixing things that break the generated d.ts files
but avoid fixing content related issues that should probably be fixed in the original docs

**Comment by bd82** [comment]
Closing for tasks cleanup, may be re-opened / created as we discuss on future tasks for this project.
