### ISSUE TITLE
Modify Demo/Docs to use jsconfig.json

### ISSUE THREAD

**Issue by bd82** [SAP/ui5-typescript#13]
https://code.visualstudio.com/docs/languages/jsconfig

**Comment by rotda** [comment]
Hi have you found a solution which work with code ? 

Code search always  in this folder an there I have no ui5-typescript
C:/Users/<user>/AppData/Local/Microsoft/TypeScript/3.4.3/node_modules

jsconfig.json
```
{
    "typeAcquisition": {
        "include": [
            "openui5/ts-types"
        ]
    }
}
```

**Comment by bd82** [comment]
Can you re-phrase your question @rotda ? I am not sure I understand.
The current demo for the JavaScript scenario works with vscode.
- https://github.com/SAP/ui5-typescript/tree/master/demos/demo-js

This demo repo uses a tsconfig.json currently.

**Comment by rotda** [comment]
Sorry . 

I try to activate the Intellisense for UI5 in vscode 
https://code.visualstudio.com/docs/nodejs/working-with-javascript#_intellisense
jsconfig.json 

`{
    "typeAcquisition": {
        "include": [
            "openui5/ts-types" also tested with "@openui5/ts-types" 
        ]
    }
}`

Error in TSServer.log

`[19:51:5.987] '@openui5/ts-types' is in missingTypingsSet - skipping...`

package.json snippet 

`"@openui5/ts-types": "^1.65.1"`

With this package it works fine :
https://www.npmjs.com/package/@types/openui5

jsconfig.json
```
{
    "typeAcquisition": {
        "include": [
            "openui5"
        ]
    }
}
```

**Comment by bd82** [comment]
o.k. I do not understand why you need the automatic type acquisition feature of VSCode.
I doubt it would work anyhow as the Types are not available via DefinitelyTyped.

All you need is a tsconfig or jsconfig file that references the types:
- https://github.com/SAP/ui5-typescript/blob/master/demos/demo-js/tsconfig.json#L7

and linking the types using JSDocs annotations:
- https://github.com/SAP/ui5-typescript/blob/master/demos/demo-js/lib/constructor-signatures.js#L1-L6

**Comment by rotda** [comment]
Thanks it goes now, thought too complicated :-)

**Comment by bd82** [comment]
JSConfig seems to be VSCode only.
- https://code.visualstudio.com/docs/languages/jsconfig
I rather keep the demo more generic, so this become irrelevant.
