### ISSUE TITLE
demo-ts compilation fails

### ISSUE THREAD

**Issue by djojoz** [SAP/ui5-typescript#162]
I currently cannot use `demo-ts`.
Here are the steps to reproduce the issue:
```
git cone https://github.com/SAP/ui5-typescript.git
cd ui5-typescript
yarn
cd demos/demo-ts
yarn
tsc
```
Result:
```
[...]

../../node_modules/@sapui5/ts-types/types/sap.ui.unified.d.ts:14348:7 - error TS1109: Expression expected.
14348 sIcon=?: sap.ui.core.URI
            ~

../../node_modules/@sapui5/ts-types/types/sap.ui.unified.d.ts:14348:8 - error TS1109: Expression expected.
14348 sIcon=?: sap.ui.core.URI
             ~
Found 160 errors.
```
The same error appears when I use  `@sapui5/ts-types` in my own project.

**Comment by bd82** [comment]
Hello @djojoz 

This project is no longer responsible for generating the type signatures.
Only for providing the generator library itself.

There seem to be a new issue in the UI5 JSON sdk that causes the `=` suffix to be added to the parameter names.
It seems to have been partially addressed in version `1.81.0` as I get "only" 95 errors with that version.

Lets continue tracking the issue in #118
