### ISSUE TITLE
None JSDoc Syntax compatible syntax in 1.65.1 API.json

### ISSUE THREAD

**Issue by bd82** [SAP/ui5-typescript#20]
Examples:
- https://github.com/SAP/ui5-typescript/commit/8d306c38355ea6a5ae81a9efb16046710f44a06a#diff-9856d1481d3d748b23ab911788888c4bR3056
-   > "type": "[ 'Array' ].<sap.ui.core.Control>"

In JSDocs this should be either:
- Array.<sap.ui.core.Control>
- sap.ui.core.Control[]

What is the cause of this divergence from the standard?

This results in many signatures not translated to "any", e.g:
- https://github.com/SAP/ui5-typescript/commit/8d306c38355ea6a5ae81a9efb16046710f44a06a#diff-8adb35e97885a884edfb7b52e3cdbd9aR1489

**Comment by codeworrior** [comment]
This must be specific to the way you generate the api.json files. In the api.json files delivered by UI5, the types look okay, e.g. https://sapui5.hana.ondemand.com/1.65.1/test-resources/sap/tnt/designtime/api.json 

I'll check whether the `ui5 tooling` caused this. Have your api.json files been created with the 1.4.1 version of the tooling or an older version?

Adding @RandomByte on CC.

**Comment by bd82** [comment]
The API.json files are generated using this command:
- https://github.com/SAP/ui5-typescript/blob/master/packages/ts-types/scripts/gen-api-json.js#L39-L41

You can reproduce this by running this script locally.
It:
1. checksout the openui5 repo with a specific tag
2. execute ui5 cli build tool.
3. collects the api.json results.

and Yes I am using 1.4.2 version of the UI5-CLI tools.

**Comment by bd82** [comment]
I cannot find this syntax in the OpenUI5 source code So i guess this is a bug with v1.4.2 of the CLI tools?

**Comment by codeworrior** [comment]
I've run the following locally in openui5/src/sap.tnt with both, `ui5 cli 1.4.1` and `1.4.2`:

```
   ui5 build jsdoc
```

and the result looks as expected:

```json
	...
	{
		"name": "getAriaLabelledBy",
		"visibility": "public",
		"returnValue": {
			"type": "sap.ui.core.ID[]"
		},
		"description": "Returns array of IDs of the elements which are the current targets of the association {@link #getAriaLabelledBy ariaLabelledBy}."
	},
	...
```

**Comment by bd82** [comment]
Interesting I will re-examine this and fully re-create the node_modules directory in my local env.

**Comment by bd82** [comment]
o.k. it looks good now.
I must have had some mixture of dependencies in node_modules that results in this strange behavior.

https://github.com/SAP/ui5-typescript/commit/88392288d272a0d666d0f0e9a20d764aa1e8961b

**Comment by bd82** [comment]
1.65.1 released with the relevant fixes.

https://www.npmjs.com/package/@openui5/ts-types/v/1.65.1

**Comment by codeworrior** [comment]
BTW: just noticed the following issue which has been reported for JSDoc 3.6.0: https://github.com/jsdoc/jsdoc/issues/1643. 
The text of the error message highly reminds me to this issue here. Maybe JSDoc 3.6.0 was still used for some reason.

**Comment by bd82** [comment]
Could be related as I've recently updated to nodejs 12.0
