### ISSUE TITLE
Where do you get or how do you generate api.json files?

### ISSUE THREAD

**Issue by rg1** [SAP/ui5-typescript#201]
The description just tells us that @ui5/dts-generator is "A low level compiler which transforms SAP UI5 api.json format". Unfortunately I can't find any indication where to find matching files or how to generate them. There are some of those files in the tests, but they don't cover all of ui5 and only one specific version. Please amend the description to tell us how to get those files.
PS: Google didn't help me either ;)

**Comment by bd82** [comment]
Hello @rg1 

This project is used to generate the TypeScript signatures for some UI5 Libraries, which are then published on npm.
- https://www.npmjs.com/package/@sapui5/ts-types

So most users are expected to consume the types from those npm packages and not use the low level generator directly.

I don't know how to generate the UI5 api.json files, nor do I know if you could use the dts-generator for 3rd party libraries.
What I do know is how to download these api.json directly from the OpenUI5 SDK.
See: - https://github.com/SAP/ui5-typescript/blob/master/test-packages/openui5-snapshot-test/package.json#L22

**Comment by rg1** [comment]
Hello Shahar,

I know that most users will probably just consume the ts-types package. However, I'm trying to replicate what you're doing here to maybe push the boundaries some more ;) So while I did figure out that the tests include a script that properly calls jsonToDTS, I missed the script that downloads the inputs. Thank you for pointing me at it. Ultimately I believe it would be most useful if you could publish the full setup required to build the ts-types package. Still I'm thankful for what's here already 👍 

Rolf

**Comment by bd82** [comment]
> Ultimately I believe it would be most useful if you could publish the full setup required to build the ts-types package

I don't actually know the full setup, that is something that happens deep inside the UI5 build systems, unlikely to even be based around nodejs tech stack even...

Maybe @petermuessig or @matz3 can help?

**Comment by codeworrior** [comment]
>  that is something that happens deep inside the UI5 build systems, unlikely to even be based around nodejs tech stack even

Exactly. Once we're done with our migration to the ui5-tooling, we'll also document this step in more detail.

**Comment by akudev** [comment]
After a loong time, I can answer the original question: just run `ui5 build jsdoc` in a UI5 library project with the ui5.yaml file properly describing the library, then the resulting api.json file will be below `dist/test-resources/_library_/_path_/_and_/_name_/designtime`.

The JSDoc build will fail when there is not a copyright notice at the beginning of each JS file (leading comment starting with `/*!`), so you might need to add it.

When the library itself is written in TypeScript (e.g. https://github.com/SAP-samples/ui5-typescript-control-library), then the ui5.yaml usually uses the transpilation target directory as src directory, so the transpilation has to be done first (in this case with `npm run build:ts`) and the result will be in `dist/test-resources/com/myorg/myUI5Library/designtime`.
But then again, transpiling TypeScript libraries to JavaScript, just to generate a TypeScript type definition again is a bit odd. :-) The [ui5-tooling-transpile](https://www.npmjs.com/package/ui5-tooling-transpile) has an option to directly generate *.d.ts files. However, you might have other reasons to generate an `api.json` file, so I am mentioning this here nevertheless.

In case of TS libraries, there is currently a problem in the babel-preset-transform-ui5 package, which removes the copyright statement, but this has been [fixed](https://github.com/ui5-community/babel-plugin-transform-modules-ui5/commit/39ab1946f08d3fc33609bd6b9ac6cda9a985c5d7) (fix will be in the next release of this plugin over the next few days).

I think this answers the original question. This does not with the end-to

**Comment by akudev** [comment]
In addition to the comment above about building api.json, the new version of the dts-generator is now also published (sources and on npm).
See https://www.npmjs.com/package/@ui5/dts-generator and https://github.com/SAP/ui5-typescript/blob/main/packages/dts-generator/docs/end-to-end-sample.md which describes both parts.

So this issue is resolved.
