### ISSUE TITLE
Method "getValue" of sap.m.Input returns sap.m.Input

### ISSUE THREAD

**Issue by hauseyo** [SAP/ui5-typescript#226]
Method "getValue" of sap.m.Input returns sap.m.Input type, but should return string type.

Environment: VS Code
@sapui5/ts-types version: 1.84.4
Type of SAPUI5 app: Freestyle
SAPUI5 version: 1.86 (latest)

<img width="267" alt="getValue" src="https://user-images.githubusercontent.com/63884278/107520947-0153dc80-6bc3-11eb-868e-a8863f7354ac.png">

**Comment by codeworrior** [comment]
Strange. This was actually an issue in OpenUI5 source code (see https://github.com/SAP/openui5/issues/2846). But this was already fixed in the 1.77 time frame.

**Comment by codeworrior** [comment]
Mhmm. I've checked the sap.m.d.ts file for 1.84.4 in our internal repo and it contains

```ts
      /**
       * Gets the input value.
       */
      // @ts-ignore
      getValue(): string;

```

Would you mind to check your local node_modules folder whether it really contains 1.84.4 of the ts-types?

**Comment by hauseyo** [comment]
> Mhmm. I've checked the sap.m.d.ts file for 1.84.4 in our internal repo and it contains
> 
> ```ts
>       /**
>        * Gets the input value.
>        */
>       // @ts-ignore
>       getValue(): string;
> ```
> 
> Would you mind to check your local node_modules folder whether it really contains 1.84.4 of the ts-types?

Sorry, I can't check it because I reinstalled node modules. Anyway, after that everything goes right, so I think the problem was in my node_modules.
![Screenshot_2](https://user-images.githubusercontent.com/63884278/107552223-3a507900-6be4-11eb-8c57-b8d75a82357b.png)

From node_modules
![Screenshot_3](https://user-images.githubusercontent.com/63884278/107552226-3b81a600-6be4-11eb-95ad-a2ddcb7f757b.png)
