### ISSUE TITLE
Log required parameters which are suspected to actually be optional.

### ISSUE THREAD

**Issue by bd82** [SAP/ui5-typescript#25]
- Initial implementation can log to console.
  - e.g: https://github.com/SAP/ui5-typescript/blob/6638b731f6ace3545709fc1fbccebb28c2db7ba6/packages/dts-generator/lib/phases/ast-fixer.js#L397-L401

- The reporting / logging should probably be implemented as a new "phase"
  Probably before the AST fixing phase: 
  - https://github.com/SAP/ui5-typescript/blob/6638b731f6ace3545709fc1fbccebb28c2db7ba6/packages/dts-generator/lib/api.js#L35-L38

**Comment by theREALdebater** [comment]
I found one:
JSONModel(oData?: any, bObserve?: boolean | undefined): JSONModel
import JSONModel from 'sap/ui/model/json/JSONModel'

**Comment by bd82** [comment]
Thanks @theREALdebater 

Do you want to make a Pull Request to fix this in OpenUI5? 😄 
 - [Relevant OpenUI5 Source code here]( https://github.com/SAP/openui5/blob/master/src/sap.ui.core/src/sap/ui/model/json/JSONModel.js#L37-L57)

**Comment by bd82** [comment]
BTW @theREALdebater I can't find any hint in the docs (e.g in the description) that these parameters should be optional, so this issue's purpose for creating a heuristic to detect such mis-documented 
methods could never detect this case.
- imho...
- Assuming Given the api.json as an input. However, a full source code analysis may be able to detect
  oData to be optional due to:
  ```javascript
     	if (oData && typeof oData == "object") {
		this.setData(oData);
	}
  ```

**Comment by theREALdebater** [comment]
> Do you want to make a Pull Request to fix this in OpenUI5?
I shall do just that.

**Comment by bd82** [comment]
I think this is outside the scope of this project and any analysis to detect incorrect docs
should be done on the OpenUI5 as the APIs docs are part of OpenUI5.
