### ISSUE TITLE
sap.uxap.d.ts: possible generation errors? (1.71.28)

### ISSUE THREAD

**Issue by mpmoeller** [SAP/ui5-typescript#280]
Hello,

I was eager trying to test the typescript support.

As I depend on 1.71.* I tried with `npm i @sapui5/ts-types@1.71.28` and a tsconfig.json including

```
...
"paths": {
      "sap/*": [
        "./node_modules/@sapui5/ts-types/index.d.ts",
      ],
      ...
}
... 
```
However when I try compiling via `tsc` I receive:
```
% tsc
node_modules/@sapui5/ts-types/types/sap.uxap.d.ts:1178:12 - error TS1138: Parameter declaration expected.
1178 mParameter,: any,

node_modules/@sapui5/ts-types/types/sap.uxap.d.ts:1182:7 - error TS1138: Parameter declaration expected.
1182 sMode
```

@bd82 shared some infos in #215 which might be an explanation to this. 

What's your take on this?
Are you looking for such feedback in order to track (possible?) human errors (hopefully not on my side :smile:)?

Best,
Martin

**Comment by petermuessig** [comment]
Hi @mpmoeller ,

thanks for your feedback. We are interested in this. But keep in mind that the types for 1.71 are not as good as the types for the latest version of OpenUI5/SAPUI5. The generator has been improved for the newer versions. For the older versions we cannot downport all the necessary changes we had to do in the JSDoc to improve the types. 

Did you try the newer versions already? 

BR,
Peter

**Comment by mpmoeller** [comment]
To be honest, no. I did not (yet) find the time to look deeper. I am closing this issue. Next try would be with some "latest" release :-)
