### ISSUE TITLE
`@sapui5/ts-types-esm` - `MockServer.setRequests` has no type for `requests` array

### ISSUE THREAD

**Issue by DetachHead** [SAP/ui5-typescript#304]
according to the docs:
```ts
    /**
     * Setter for property `requests`.
     *
     * Default value is is `[]`
     *
     * Each array entry should consist of an object with the following properties / values:
     *
     *
     * 	 - **method : "GET"|"POST"|"DELETE|"PUT"**
     *  (any HTTP verb)
     * 	 - **path : "/path/to/resource"**
     *  The path is converted to a regular expression, so it can contain normal regular expression syntax. All
     * regular expression groups are forwarded as arguments to the `response` function. In addition to this,
     * parameters can be written in this notation: `:param`. These placeholder will be replaced by regular expression
     * groups.
     * 	 - **response : function(xhr, param1, param2, ...) { }**
     *  The xhr object can be used to respond on the request. Supported methods are:
     *  `xhr.respond(iStatusCode, mHeaders, sBody)`
     *  `xhr.respondJSON(iStatusCode, mHeaders, oJsonObjectOrString)`. By default a JSON header is set for response
     * header
     *  `xhr.respondXML(iStatusCode, mHeaders, sXmlString)`. By default an XML header is set for response header
     *
     *  `xhr.respondFile(iStatusCode, mHeaders, sFileUrl)`. By default the mime type of the file is set for
     * response header
     */
```
but it's type is just `object`:
```ts
setRequests(
      /**
       * new value for property `requests`
       */
      requests: object[]
    ): void;
```

**Comment by codeworrior** [comment]
Well, this is rather an issue in the `MockServer` [source code](https://github.com/SAP/openui5/blob/master/src/sap.ui.core/src/sap/ui/core/util/MockServer.js#L132) and needs to be fixed there. It just says

```js
  /*
   * ...
   * @param {object[]} requests new value for property <code>requests</code>
   * ...
   */
```

Would you mind to open an issue there? I know you already mentioned that you're unsure where to open issues reg. the types. Topics like the broken links are indeed issues of the transformation, whereas wrong / insufficiently described types usually are a problem of the source.

**Comment by codeworrior** [comment]
Thanks!

**Comment by DetachHead** [comment]
@codeworrior re-opening this because although https://github.com/SAP/openui5/issues/3396 was closed, it seems the type hasn't yet been updated as of the latest `@sapui5/ts-types-esm` version (1.96.1)

**Comment by akudev** [comment]
By default, fixes will only go into new minor releases, not in patch versions.
The fix (https://github.com/SAP/openui5/commit/673ea04afd8a6ff14824d7e2e2dbc9027d2c668b#diff-2c1e10c2936aeacdc409f7a8d3785deba7d54a225fe657db01dbbf90b9f33b5f) apparently has missed the codesplit for the 1.97 release (I still see the old documentation in the 1.97 definitions) and should hence be in 1.98 in ~4 weeks. Please re-open in case it is not.
Thanks!

**Comment by akudev** [comment]
Actually it's not 4 weeks, but 8 weeks: the release around X-Mas is skipped and 1.98 is scheduled for around January 26th, sorry.
