### ISSUE TITLE
`@sapui5/ts-types-esm` - `Opa5.waitFor` `options.actions` should be optional

### ISSUE THREAD

**Issue by DetachHead** [SAP/ui5-typescript#306]
```ts
actions: Function | Array<() => void> | Action | Action[];
```

it doesn't seem to be mandatory, see all the examples [in the docs](https://sapui5.hana.ondemand.com/#/api/sap.ui.test.Opa5%23overview) where `waitFor` is called without an action

i see where it's defined [here](https://github.com/SAP/openui5/blob/master/src/sap.ui.core/src/sap/ui/test/Opa5.js#L574) but as far as i can tell the documentation in the source code doesn't appear to control whether the generated types are mandatory or not

**Comment by petermuessig** [comment]
Thanks for your feedback. The TS support for the testing related APIs is still work in progress. BTW: did you also use the `@sapui5/ts-types` for your project or did you use the ESM types `@sapui5/ts-types-esm`?  

As you report quite some issues here, I am getting interested in how you are using the types? How are your projects setup? What toolchain do you use? Which IDE? And, really the classic Global types or the ESM types? Would it be possible for you to share some infos? 🙇‍♂️

**Comment by DetachHead** [comment]
@petermuessig thanks for the response! to be honest i'm not all that familiar with ui5, but since i'm good with typescript i'm helping a ui5 developer convert his project to typescript so there's probably quite a few things i'm doing wrong lol. to answer your questions:

> How are your projects setup?

mainly like [the `ui5-typescript-helloworld` project](https://github.com/SAP-samples/ui5-typescript-helloworld). i'm converting a project that appears to be based on [this worklist example](https://github.com/SAP/openui5/tree/2bba4ea6a49332575a87de443efdc6893d66b153/src/sap.m/test/sap/m/demokit/tutorial/worklist/06)

> Which IDE?

i primarily use webstorm, but sometimes vscode

> And, really the classic Global types or the ESM types?

using `@sapui5/ts-types-esm`, however there's some stuff in this codebase that seems to use the globally defined `sap` object:
```ts
const sManifestUrl = sap.ui.require.toUrl(_sAppModulePath + 'manifest.json')
```

**Comment by DetachHead** [comment]
seems this is fixed in the latest version of `@sapui5/ts-types-esm`, thanks!

**Comment by petermuessig** [comment]
@DetachHead thanks for your fast feedback and the answers for my questions.

Some of the Globals can't be avoided easily unfortunately like `sap.ui.require.toUrl` is often used to calculate the URL to resource paths and `sap.ui.require` accesses the APIs of the UI5 loader.  Some of the APIs could be shifted to ES module APIs but not for all something equivalent is available.
