### ISSUE TITLE
`@sapui5/ts-types` - no types for `sap/ui/fl/FakeLrepConnectorLocalStorage` module

### ISSUE THREAD

**Issue by DetachHead** [SAP/ui5-typescript#309]

**Comment by codeworrior** [comment]
This is not a bug. `FakeLrepConnectorLocalStorage` is a [private API](https://github.com/SAP/openui5/blob/master/src/sap.ui.fl/src/sap/ui/fl/FakeLrepConnectorLocalStorage.js#L23), therefore no types are generated.
