### ISSUE TITLE
@types/openui5 - missing type information for sap/ui/Device

### ISSUE THREAD

**Issue by marcelschork** [SAP/ui5-typescript#311]
Tested with @types/openui5 version 1.96.0.
![image](https://user-images.githubusercontent.com/63337737/143476196-34b69b89-2fd6-4163-b24e-1eaad5cae95a.png)

**Comment by petermuessig** [comment]
Thanks @marcelschork for reporting this issue.

An alternative with typing right now would be using the `Device.browser` API like this:

```ts
import { browser } from "sap/ui/Device";

const isMobile = browser.mobile;
```

**Comment by akudev** [comment]
Hi Marcel, thanks for reporting. I can confirm that on Device basically nothing is defined. For the time being you can import the properties of Device, which are named exports:
```ts
import { browser } from "sap/ui/Device";
```
On those, everything you need should be defined.
