### ISSUE TITLE
@openui5/ts-types-esm: Missing types for MessageBox.warning

### ISSUE THREAD

**Issue by DerLordi** [SAP/ui5-typescript#312]
The types for MessageBox.warning are not equal to the definition from the API Reference. 
API Reference says that you kann use the following structure: 

```
MessageBox.warning("test", {
    actions: [MessageBox.Action.OK, MessageBox.Action.CANCEL],
    onClose: function (action: Action) {
       // do something
    }
})
```

But typescript compiler says that mOptions are not including the actions-parameter.
mOptions are only allowed for MessageBox.show - and that is not correct.

**Comment by codeworrior** [comment]
Which version of @openui5/types-esm do you use? This was a problem in the source documentation, discussed (and fixed) [here](https://github.com/SAP/openui5/issues/3286). So it should only occur in older versions (< 1.93).

**Comment by DerLordi** [comment]
I use "@openui5/ts-types-esm": "1.90.1".
It is the generated package.json from the easy-ui5 plugin for the yo-generator.

I`ll try to update to the latest version and check again. Thank you

**Comment by DerLordi** [comment]
yep - new version fixes this issue. Issue can get closed.

**Comment by petermuessig** [comment]
I will update the ts-app template to always suggest the highest version of the types.
