### ISSUE TITLE
@ui5\ts-interface-generator - command not found

### ISSUE THREAD

**Issue by lemaiwo** [SAP/ui5-typescript#319]
After installing @ui5\ts-interface-generator I get the following error when running the generator:

C:\ui5\>npx @ui5/ts-interface-generator --watch
npx: installed 18 in 2.736s
command not found: ts-interface-generator

Any idea what I'm missing?

Kr, Wouter

**Comment by akudev** [comment]
Thanks for the feedback, I'm going to look into this!

**Comment by akudev** [comment]
I think the binary is missing in the package. Please for the time being try:
```sh
node node_modules/@ui5/ts-interface-generator --watch
```

**Comment by akudev** [comment]
Issue should be fixed with `@ui5/ts-interface-generator@0.2.1` now. Thanks again and sorry!

**Comment by lemaiwo** [comment]
This is fixed, thanks! Now I'm facing another problem, I will create another issue for that.
