### ISSUE TITLE
npmjs releases: "latest" tag does not always point to the latest release

### ISSUE THREAD

**Issue by akudev** [SAP/ui5-typescript#320]
"latest" always points to the last-released version, not to the highest version number.
(e.g. on https://www.npmjs.com/package/@openui5/ts-types-esm)
As soon as a patch is released for a lower version, "latest" points to that patch.

**Comment by petermuessig** [comment]
The next release of the types will ensure to update the `latest` tag properly. Just waiting for the next release and will close the ticket once the release was done and the `latest` tag is set correct.

**Comment by petermuessig** [comment]
`latest` works now properly: https://www.npmjs.com/package/@openui5/ts-types
