### ISSUE TITLE
ts-types-esm: sap.f.FlexibleColumnLayoutSemanticHelper UI state object structure not defined

### ISSUE THREAD

**Issue by akudev** [SAP/ui5-typescript#325]
This structure is only explained in the documentation fulltext. The JSDoc used for the TypeScript definition just says "object".
Used for e.g. the methods getNextUIState and getCurrentUIState.

Tracked by internal ticket 2180434276

**Comment by kineticjs** [comment]
The JDoc update that addresses this issue will be available in SAPUI5 1.99

**Comment by akudev** [comment]
See https://github.com/SAP/openui5/commit/ea0b15cda111284864c863bbad9b20225bea6134
