### ISSUE TITLE
ESLint Report - Error "Parsing error: Cannot find module 'babel-preset-transform-ui5' blocks merge

### ISSUE THREAD

**Issue by eiseleh** [SAP/ui5-typescript#326]
We have a Fiori Element app for which we use typescript since a long time without direct tool support.
I migrated the app now according the guideline 
https://sap.github.io/ui5-typescript/#how-to-convert-an-existing-ui5-app-to-typescript

The app works fine in BAS. However, the eslint-run in jenkins report errors "Parsing error: Cannot find module '@babel/preset-env' ... which blocks us from merging. 
See:
[link removed]
The folder @Babel/preset_env is below our node_modules folder in the project.

**Comment by akudev** [comment]
Hi, can you please provide a link to your sources of the app?
As it is likely going to be an internal link, please contact me directly via e-mail.
I also removed a part of your above comment for this reason.

**Comment by eiseleh** [comment]
Hi
The source is located in 
https://github.tools.sap/S4-FIORI-CORE-4/i2d.qm.fmea.manages1
The relevant pull-request  is
https://github.tools.sap/S4-FIORI-CORE-4/i2d.qm.fmea.manages1/pull/86
I'm using BAS where eslint seems not working.
Best regards,

**Comment by akudev** [comment]
This issue was resolved in direct communication: the CI check ran in production mode, where the dev-dependencies like Babel etc. were not available.
