### ISSUE TITLE
ts-types-esm sap.ui.core.format.NumberFormat.getScale

### ISSUE THREAD

**Issue by nlunets** [SAP/ui5-typescript#339]
This method is a relatively public one considering the naming but was not tagged public nor private nor anything and as such is missing.

Shoudn't it be tagged public ?

**Comment by tobiasso85** [comment]
Yes, indeed it should be public.

**Comment by tobiasso85** [comment]
was fixed with:
https://github.com/SAP/openui5/commit/ece96e7ee7daa86b3883951a19b7ad5dae187401
