### ISSUE TITLE
ui5-ts-types: NavContainer .to has incorrect parameters

### ISSUE THREAD

**Issue by nlunets** [SAP/ui5-typescript#344]
.to method expect 4 parameter but only 1 is mandatory, the types / jsdoc do not reflect that.

**Comment by codeworrior** [comment]
Should be fixed with https://github.com/SAP/openui5/commit/052ba74c7e5e1d066f583230f5c129442992f25f and show up in the TS signatures with 1.100

**Comment by akudev** [comment]
Verified fixed
