### ISSUE TITLE
sap.uxap.ObjectPageLayoutRenderer is not defined in ts-types

### ISSUE THREAD

**Issue by Revest117** [SAP/ui5-typescript#350]
As mentioned above, the renderer for ObjectPageLayout is missing.

**Comment by codeworrior** [comment]
This is a duplicate of the more general https://github.com/SAP/ui5-typescript/issues/340 . 

Renderers by intention are not public in UI5 and therefore don't appear in the TypeScript signatures. See #340 for possible ways to inherit a renderer, if that is your use case.
