### ISSUE TITLE
ODataModel v4 bindContext parameters in error

### ISSUE THREAD

**Issue by lemaiwo** [SAP/ui5-typescript#355]
Hi,

We noticed that TypeScript is raising errors when we try to use bindContext on the ODataModel v4 with the expand parameter.
![MicrosoftTeams-image (9)](https://user-images.githubusercontent.com/5943183/167944102-afbe30b6-32a8-4676-83d9-c458d2c5e3d7.png)

Although this is supported in the documentation:
https://ui5.sap.com/1.96.8/#/api/sap.ui.model.odata.v4.ODataModel%23methods/bindContext
![image](https://user-images.githubusercontent.com/5943183/167944227-59594800-5571-41f1-af51-e8b32d833f3e.png)

Probably not a TypeScript issue as this the $expand is not mentioned with its own property in the documentation. Nevertheless, it should not raise an error if it is allowed to use it.

Kr, Wouter

**Comment by akudev** [comment]
Fixed for next release.
