### ISSUE TITLE
New create method missing for ODataListBinding

### ISSUE THREAD

**Issue by Fjaoos** [SAP/ui5-typescript#360]
Hi all,

in 1.98.0 the v2 ODataListBinding got a new create method: https://sapui5.hana.ondemand.com/#/api/sap.ui.model.odata.v2.ODataListBinding%23methods/create

This is not yet in the definition.

Thank you for your work.

**Comment by codeworrior** [comment]
Mhmm, how are you using the UI5 types? 
Looking at https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/master/types/openui5/sap.ui.core.d.ts , I see the ODataListBinding#create method.
