### ISSUE TITLE
`sap.ui.Device.system` is undeclared

### ISSUE THREAD

**Issue by sap-sebelao** [SAP/ui5-typescript#362]
Example:
```
import Device from "sap/ui/Device"

if(Device.system.tablet) { // TS: Property "system" does not exist on type "Device"
     ...
}
```

TS does not recognize the property `system`.

It is part of the public API
https://sapui5.hana.ondemand.com/#/api/sap.ui.Device.system
So I see no reason why it should not be supported.

**Comment by petermuessig** [comment]
Fixed with UI5 types `1.115.0`, see #311 

Closing the issue.
