### ISSUE TITLE
`sap.ui.comp.filterbar.FilterItem.getControl` has return type `void`

### ISSUE THREAD

**Issue by sap-sebelao** [SAP/ui5-typescript#363]
This is a really bad choice for a return type, as void can't even be cast to another type directly, it forces me to cast it via unknown first, like so: `oFilterItem.getControl() as unknown as Control;`.

**Comment by akudev** [comment]
Hi @sap-sebelao , thanks for reporting!
A fix has been prepared and is in review internally (Change-Id: Ic2d0db623d41bfe020513e092f6346ecb67a814b).

**Comment by akudev** [comment]
The fix was now submitted to master, will be in 1.105.
Thanks again!
