### ISSUE TITLE
`sap.m.Select.getSelectedIndex` has no declaration

### ISSUE THREAD

**Issue by sap-sebelao** [SAP/ui5-typescript#364]
Example:
```
import Select from "sap/m/Select";

let select = new Select();
select.getSelectedIndex(); // TS: Property 'getSelectedIndex' does not exist on type 'Select'.
```

I looked into the SDK and it does not seem to be part of the documentation either - which would point to the fact that this is not a public method, _however_ I looked directly into the source of truth - the sap.m.Select code itself, and there is no `@private` tag:

```
/**
 * Retrieves the index of the selected item from the aggregation named <code>items</code>.
 *
 * @returns {int} An integer specifying the selected index, or -1 if no item is selected.
 * @since 1.26.0
*/
Select.prototype.getSelectedIndex = function() {
    var oSelectedItem = this.getSelectedItem();
    return oSelectedItem ? this.indexOfItem(this.getSelectedItem()) : -1;
};
```

So this seems strange, it's JSDoc does not seem to imply that this method is private, but it does not show up in SDK and the generated `.d.ts` anyway.

**Comment by codeworrior** [comment]
Or, @kineticjs and @jdichev can you please take a look or forward accordingly?

**Comment by kineticjs** [comment]
Hello @sap-sebelao ,
Thank you for sharing this UI5 code related finding. We've created an internal incident 2280121286 to investigate it further.
Regards,
Diana

**Comment by plamenivanov91** [comment]
Hello @sap-sebelao ,

The method in question is not related to a public property and it's meant to be used internally, we marked it as private.

Regards,
Plamen
