### ISSUE TITLE
ts-interface-generator does not generate interfaces for classes without added aggregations/props/events

### ISSUE THREAD

**Issue by dfenerski** [SAP/ui5-typescript#368]
Consider the following class:
<pre>
/**
 * @name com.namespace.SomeListItem
 */
export default class SomeListItem extends ColumnListItem {
	static readonly metadata = {
		library: 'com.namespace',
	};
	public firePress() {
		super.firePress();
		try {
			const jqRef = this.$();
			jqRef.removeClass('sapMPopinHovered');
		} catch (e) {
			console.error(e);
		}
		return this;
	}
}
</pre>

The generator completely skips it, and when imported typescript remains blind for the constructor signatures.

Is this planned, should I add mock props, or maybe manually write declaration to be merged?

**Comment by akudev** [comment]
@dfenerski I haven't checked in detail, but right now I think you are right: because of the constructor signature the interface should also be generated when a class does not add anything to the interface. I'll check as soon as UI5con stress allows.

**Comment by akudev** [comment]
@dfenerski  on second glance, what exactly is not working or missing?

When I e.g. use the app in the ["custom-controls" branch of the hello word app](https://github.com/SAP-samples/ui5-typescript-helloworld/tree/custom-controls) and add another control which inherits from `MyControl` but does not specify any new properties etc., then its constructor works perfectly fine as far as I see. It just inherits the one from the parent class, as expected.

![image](https://user-images.githubusercontent.com/4866568/179946767-45c6aacd-a4ff-4549-96d4-6e163525a31a.png)

For reference: the code where such classes are ignored is [here](https://github.com/SAP/ui5-typescript/blob/main/packages/ts-interface-generator/src/interfaceGenerationHelper.ts#L462). In fact there is already a "FIXME" about exactly this topic, but right now it looks like this can just be removed.

**Comment by dfenerski** [comment]
@akudev you are right, it is working fine. I got confused because only generated props need an additional interface; instance methods do not due to standard `import` / `export` statements during devtime. Thanks for the responsiveness!
