### ISSUE TITLE
ts-interface-generator does not parse properties of type `Array` properly

### ISSUE THREAD

**Issue by dfenerski** [SAP/ui5-typescript#370]
Consider the following class:
<pre>
import ComboBox from 'sap/m/ComboBox';

/**
 * @name my.namespace.MyComboBox
 */
export default class MyComboBox extends ComboBox {
	static readonly metadata = {
		library: 'my.namespace',
		properties: {
			filters: {
				type: 'sap.ui.model.Filter[]',
				defaultValue: [],
			}
		},
	};
}
</pre>

The `MyComboBox.gen.d.ts` file has then this auto-generated line: `import Filter[] from "sap/ui/model/Filter[]";`, i.e. when the aggregation is of type `Something[]`, the generator considers the characters `[` and `]` to be part of the name.

**Comment by dfenerski** [comment]
There is warning from the generator when this occurs: 
![image](https://user-images.githubusercontent.com/48520530/177393311-26273075-8bf0-4c62-918f-0dd7c1ab2dc8.png)

**Comment by akudev** [comment]
Well, in general it is better to use an aggregation of Elements instead of an array property, so changes within the array/list also trigger invalidation, but yeah, in some cases arrays are needed, so this needs to be fixed. Thanks for reporting!

**Comment by akudev** [comment]
FYI: the "next release" (0.5.1) was done this week.
