### ISSUE TITLE
metadata bindable does not add convenience functions

### ISSUE THREAD

**Issue by Revest117** [SAP/ui5-typescript#372]
Adding the bindable tag to metadata properties or aggregations element does not result in a bind or other convenience functions in the gen.d.ts

**Comment by akudev** [comment]
@Revest117 Actually it does work for aggregations, as can be seen in this sample output:
https://github.com/SAP/ui5-typescript/blob/main/packages/ts-interface-generator/src/test/testdata/sampleControl/SampleControl.gen.d.ts#L43

But you are right that it is missing for properties. Thanks!
