### ISSUE TITLE
ManagedObject.prototype.getModel returns Model is wrong

### ISSUE THREAD

**Issue by nlunets** [SAP/ui5-typescript#380]
ManagedObject.prototype.getModel  returns Model based on the jsdoc but in reality it will return Model | undefined

It would be nice to update the jsdoc to reflect that :)

**Comment by akudev** [comment]
Being fixed now, but please consider opening OpenUI5- or internal tickets for such clear cases in the future, so the code owners will take care (and learn about the importance of correct documentation while doing so).

**Comment by akudev** [comment]
I'm sure you will. We have done a round of automated searching and fixing recently, but only considered the return value comment text. Even this resulted in ... was it ~~100? ... fixes. Code analysis would likely bring up more hits and still miss many.

Internal tickets have lower dispatching overhead (would be anyway opened for GitHub tickets), so please create those.

**Comment by akudev** [comment]
Fixed via https://github.com/SAP/openui5/commit/b8ac5506780690ebc7bc18841797128b648a584b
