### ISSUE TITLE
"Latest" version of types npm package incorrect

### ISSUE THREAD

**Issue by BenReim** [SAP/ui5-typescript#384]
**Describe the bug**
```shell
$ npm outdated
Package                           Current   Wanted    Latest  Location                                       
@sapui5/ts-types-esm              1.109.3  1.109.3  1.102.13  node_modules/@sapui5/ts-types-esm              
```

**Expected behavior**
The latest version should point to the latest package version.

**Comment by akudev** [comment]
Absolutely right. So far not addressed by the responsibles, but maybe this gives another push.

**Comment by nhebling** [comment]
I experience the same and wondered if its "just a bug" or if there is an issue detected in the higher releases and the idea is to use this to "rollback" temporarily to a previous version.

```
$ npm outdated                                                                                                                                                                                    
Package               Current   Wanted   Latest  Location                           
@sapui5/ts-types-esm  1.111.0  1.111.0  1.108.9  node_modules/@sapui5/ts-types-esm 
```

**Comment by codeworrior** [comment]
This is rather bug, not a conscious decision. All @sapui5 packages are currently published in a way that the last published artefact (in time) gets the `latest` label, independent from its version. This is npm's default behaviour.

To fix it, lower versions have to be assigned another label explicitly, but the internal release processes have not yet been adapted to do so.

This is internally tracked in our backlog as CPOUI5FOUNDATION-58.

**Comment by akudev** [comment]
This is fixed now, see https://www.npmjs.com/package/@sapui5/types?activeTab=versions (well, that's the new name with only one release, but the same is valid for the legacy name: https://www.npmjs.com/package/@sapui5/ts-types-esm?activeTab=versions)
The "latest" tag should be right and there is also a "latest-1.x" tag for each minor release.
