### ISSUE TITLE
Controls are missing members of base classes

### ISSUE THREAD

**Issue by BenReim** [SAP/ui5-typescript#389]
**Describe the bug**
```javascript
    const myDateTimePicker = /**@type {import('sap/m/DateTimePicker').default} */ (this.byId("dateTimePicker"));

    // Property 'setMaxDate' does not exist on type 'DateTimePicker'. Did you mean 'getMaxDate' ?ts(2551)
    myDateTimePicker.setMaxDate(new Date());
```

**Additional context**
"@sapui5/ts-types-esm": "^1.111.0"

**Comment by codeworrior** [comment]
That's an issue in the sources of `sap/m/DatePicker.js`. It documents the methods setMin/MaxDate, but without marking them as @public. This essentially makes them @private in UI5, therefore they're not included in the type definitions.

Would you please open an issue in openui5? Colleagues have to fix their JSDoc.

**Comment by BenReim** [comment]
Sure, I have created the following issue:  https://github.com/SAP/openui5/issues/3709
