### ISSUE TITLE
TypeScript support for SAP Web Ide Full stack

### ISSUE THREAD

**Issue by Tapishnu** [SAP/ui5-typescript#41]
Hi,

Is there a type script support in Sap web iIDE full stack? Can you give me any details if it is available.

Tapishnu

**Comment by bd82** [comment]
Hi @Tapishnu 

I am not familiar with any such support...

**Comment by htammen** [comment]
Hi @Tapishnu,
I don't think that SAP Web IDE does support it. Never heard that they have build in a tsc task. The only adjustment I've heard of is to the Grunt build but I guess you also want to have support at dev time?
