### ISSUE TITLE
How to create a typed view in SAP UI5 typescript

### ISSUE THREAD

**Issue by swayongshen** [SAP/ui5-typescript#422]
** IMPORTANT **
This tracker is for issues caused by the tools maintained here (type definition generator and ts-interface generator for control development support).
But if the bug is within the original OpenUI5/SAPUI5 code/JSDoc, then please report the issue there!

Example: if a UI5 API is defined wrongly in the TypeScript type definitions but the same wrong definition can also be found in the [UI5 API documentation](https://ui5.sap.com), then the issue originates probably from the JSDoc inside the UI5 code, from which both are generated, and needs to be reported in the [OpenUI5 issue tracker](https://github.com/SAP/openui5/issues/new) or the one for SAPUI5, respectively.

**Describe the bug**
Seeking resources to learn how to create a [typed view](https://sapui5.hana.ondemand.com/sdk/#/topic/e6bb33d076dc4f23be50c082c271b9f0.html) in order to do XML processing for conditional rendering (`<template:if>` `<template:else>`). Currently all tutorials are referencing the JS way to do it

**Comment by akudev** [comment]
Sorry for the delay, I was a bit confused by how typed views are related to XML preprocessing, as typed views are JSViews and the preprocessing applies to XMLViews.

But the UI5 2.x guidelines say "use typed views when using JSViews", so a sample should indeed be provided.

**Comment by akudev** [comment]
Alright, another big delay, sorry, but basically the answer is that there is nothing special at all. 

### Typed Views in TypeScript

On the one hand, a typed View in TypeScript is a straightforward conversion from the JS code - inherit from View and have a `createContent` method:
```ts
import Control from "sap/ui/core/Control";
import View from "sap/ui/core/mvc/View";

/**
 * @namespace my.app.view
 */
export default class Items extends View {
    async createContent(): Promise<Control> {
        // ...
    }
}
```
So this should satisfy the "how to create a typed view?" part, which is relevant as the guidelines say "use typed views when using JSViews".

### XML Preprocessing

On the other hand, you want to use XML templating. Well, XML templating is by its nature not related to JS/typed views, but to XMLViews. However, the documentation states that "*there is no way to declare that the XML Preprocessor should run on the target view of a route. Instead, you should define a as the route's target and use that view's createContent method to create an XML view with templating.*"
This sounds like a sort of workaround, but is one of the reasons to indeed combine both, even if this means nesting two views into each other. There might also be more use-cases, where something around the view needs to be processed for proper setup.

But in any case, this part is no different in TypeScript, the code is identical to what is written in JavaScript. 

One example is currently being created for a tutorial at https://github.com/SAP-samples/ui5-mdc-json-tutorial/blob/mdc-json-advanced/ex6/webapp/view/MountainsTemplate.ts

This branch might be removed once it is merged to the main branch, then you should find the code somewhere there. But to be on the safe side, here is the current state of that View for reference:
```ts
import Control from "sap/ui/core/Control";
import View from "sap/ui/core/mvc/View";
import XMLView from "sap/ui/core/mvc/XMLView";
import JSONPropertyInfo from "../model/metadata/JSONPropertyInfo";

/**
 * @namespace mdc.tutorial.view
 */
export default class Mountains extends View {
    async createContent(): Promise<Control> {
        return XMLView.create({
            id: "mountains",
            preprocessors: {
                xml: {
                    models: {
                        pim: {
                            PropertyInfo: JSONPropertyInfo
                        }
                    }
                }
            },
            viewName: "mdc.tutorial.view.Mountains"
        });
    } 
}
```

It does not use templating right now, but adding something like the templating namespace `xmlns:template="http://schemas.sap.com/sapui5/extension/sap.ui.core.template/1"` and a simple template block like `<template:if test="{= false}">` to `Mountains.view.xml` works fine.

As there does not seem to be anything specific to this topic, only the standard UI5-class-to-ES6-class conversion, which applies to everything in UI5, I am closing this ticket without providing an extension to the official documentation - it would just say "do it like everything else". In general, more TS code samples will come, though.
