### ISSUE TITLE
Missing type definition for `sap.m.table.ColumnWidthController`

### ISSUE THREAD

**Issue by junwei-tj** [SAP/ui5-typescript#423]
**Describe the bug**
In `sap.m.d.ts`, there isn't a declaration for `sap.m.table.ColumnWidthController`, hence it is not possible to import this class. This class is used for the personalization of responsive tables, as shown here: https://openui5.hana.ondemand.com/entity/sap.m.p13n.Engine/sample/sap.m.sample.p13n.Engine/code

In the UI5 docs, `sap.m.table.ColumnWidthController` has already been documented (https://openui5.hana.ondemand.com/api/sap.m.table.ColumnWidthController), hence my reason for posting this as an issue here. My apologies if this should be posted in the OpenUI5 repo instead.

**Comment by codeworrior** [comment]
What version of the `sap.m.d.ts` file are you referring to? Looking for example at [DefinitelyTyped](https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/master/types/openui5/sap.m.d.ts), I see a module `sap/m/table/ColumnWidthController`.

**Comment by junwei-tj** [comment]
I am using `1.118.0`. Is it perhaps only introduced after `1.118.0`?

**Comment by codeworrior** [comment]
The API unfortunately does not contains a `@since` tag, but as far as I can see, it was added only in 1.120 (with SAP/openui5@66294feabb823ab33c14efebcc131919134e36db)

**Comment by junwei-tj** [comment]
I see! Then perhaps this is a non-issue. Thanks for the help!
