### ISSUE TITLE
Consider to use Type Aliases for UI5 data types

### ISSUE THREAD

**Issue by codeworrior** [SAP/ui5-typescript#44]
UI5 provides several ways to [derive new simple types from built-in types](https://openui5nightly.hana.ondemand.com/topic/ac56d92162ed47ff858fdf1ce26c18c4).

- One way are string based **enums**, which perfectly translate to `TypeScript` string enums. They usually have a global name and that name denotes both, the type as well as the object that contains the enum values. 
- Mapping UI5's **Array types** to `TypeScript`, is trivial, too.
- But **pattern-based specializations of type `string`** are harder to map. Their names have a two-fold meaning: 
  - _DataType object_: the global property with the same name as the type points to an object which is an instance of `sap.ui.base.DataType`. It will be used by the UI5 runtime to check whether a given value (string) matches the type's constraints (pattern).
  - _type name_: the same name can be used as `type` of control properties. New values for the property are then checked by the runtime against the type's constraints. Similarly, the type name can be used in JSDoc for method  or event parameter types or method return types. 

For the TS type declarations, the focus IMO should be on the _type name_ aspect. Currently, the dts-generator maps those types to interfaces, but a mapping to type aliases seems to be more appropriate to me. None of the suitable string values will implement the interface. 

Example for `sap.ui.core.CSSSize`:

```ts
type CSSSize = string
```

The necessary information can be found in the api.json
```js
{
	"kind": "namespace",
	"name": "sap.ui.core.CSSSize",  // alias name
	"visibility": "public",
	"ui5-metadata": {
		"stereotype": "datatype",   // indicator for the data type case
		"basetype": "string",                // base type to be aliased
		"pattern": "^(auto|inherit|[-+]? ... )$"
	}
}
```

As the constraints (pattern) cannot be expressed in `TypeScript`, adding the documentation to the alias seems quite important to me. Currently, the interfaces for types come without any documentation.

**Comment by codeworrior** [comment]
BTW: if checking the `"ui5-metadata"/"stereotype"` seems like a too high level of coupling: UI5 could also use `@typedefs` (without properties) to represent such data types. It might take a while until all types are migrated. But a `@typedef` looks more appropriate to me than the current `@namespace` tags. 

I'll check whether the UI5 SDK can consume such typedefs, too. 

This doesn't change the initial proposal to represent data types as type aliases. It just might make detecting them more straight forward.

**Comment by bd82** [comment]
I believe the representation as `interfaces` was not meant to provide a good translation.
Rather it was meant as a quick solution to generate "correct" signatures, because if he
CSSSIze is translated as a `namespace` it cannot be referenced as a **type** elsewhere and causes compilation errors.

You suggestion will be an improvement particularly to include the relevant docs for the string type constraints.

**Comment by bd82** [comment]
Closing for tasks cleanup, may be re-opened / created as we discuss on future tasks for this project.
