### ISSUE TITLE
`@sapui5/ts-types-esm` - `sap/ui/core/Core` is incorrectly exported as an instance instead of a class

### ISSUE THREAD

**Issue by DetachHead** [SAP/ui5-typescript#443]
**Describe the bug**
`sap/ui/core/Core` seems to be exported as an instance of the `Core` interface, instead of a class:
```ts
declare module "sap/ui/core/Core" {
    interface Core {
        // ...
    }
    const Core: Core
    export default Core
}
```
this means that it cannot be instantiated when imported:
```ts
import Core from 'sap/ui/core/Core'

// typescript error:
// This expression is not constructable.
//   Type 'Core' has no construct signatures.
const core = new Core()
```
**Expected behavior**
it should probably be something like this:
```ts
declare module "sap/ui/core/Core" {
    export default class Core {
        // ...
    }
}
```

**Additional context**
at runtime, `Core` is a class that needs to be instantiated:

![image](https://github.com/SAP/ui5-typescript/assets/57028336/b10d8462-10e8-4a14-bcf7-c32ba9cc0feb)

**Comment by codeworrior** [comment]
Eh, no.

At runtime, the Core module returns an instance of sap.ui.core.Core. Each call to the constructor (if you get access to it via globals) would even return the same singletons instance. 

Check the [source](https://github.com/SAP/openui5/blob/master/src/sap.ui.core/src/sap/ui/core/Core.js#L3331-L3342);
```js 
	/*
	 * Create a new (the only) instance of the Core and return it's interface as module value.
	 *
	 * Do not export the module value under the global name!
	 *
	 * Note that the Core = EventProvider.extend() call above already exposes sap.ui.core.Core.
	 * This is needed for backward compatibility reason, in case some other code tries to enhance
	 * the core prototype. Once global names are switched off, such extension scenarios are
	 * no longer supported.
	 */
	oCore = new Core().getInterface();
	return oCore;
```

**You must not create new instances but rather use the export of the module.**

But I understand that the [documentation](https://ui5.sap.com/#/api/sap.ui.core.Core%23events) falls short to explain this. In earlier versions, this was slightly better, but the example went lost with a recent refactoring (most likely as the example was based on an API that uses globals):
<img width="708" alt="image" src="https://github.com/SAP/ui5-typescript/assets/9580095/df21c007-392f-4b03-91f7-37b1da8c0a80">

I'll take care of the documentation aspect, but that's a topic for `openui5`, not `ui5-typescript`. The types are correct and reflect the intended usage of the Core.

I therefore close this issue.
