### ISSUE TITLE
i can't find a way to use typescript and the flp sandbox launchpad

### ISSUE THREAD

**Issue by yosi-fridman** [SAP/ui5-typescript#452]
i can't find a way to use typescript and the flp sandbox launchpad,
is there any support for this?

**Comment by akudev** [comment]
A bit more context would be helpful.
Whatever you do with TypeScript, in the end the application is transpiled to JavaScript. Whatever you did until now using JavaScript should also be possible with this resulting JavaScript. Doesn't work? Check how it looks and how it normally looked with plain JavaScript and what's the difference. This should guide you to the reason for any problem.

**Comment by akudev** [comment]
In general, this is not a support forum, though. So please clearly demonstrate a bug or a behavior that should be improved, then we can continue here.

**Comment by akudev** [comment]
no response.
