### ISSUE TITLE
Missing types for sap.ui.qunit.utils.nextUIUpdate and waitForThemeApplied

### ISSUE THREAD

**Issue by LukasHeimann** [SAP/ui5-typescript#459]
**Describe the bug**
I want to use sap.ui.qunit.utils.nextUIUpdate and waitForThemeApplied as replacements for deprecated Core APIs, as advertised by the ui5linter. However, `@sapui5/types` is missing the modules -- perhaps because it contains neither a `sap.ui.d.ts` nor a `sap.ui.qunit.d.ts`. Thus, when importing `import nextUIUpdate from "sap/ui/qunit/utils/nextUIUpdate";`, and error message appears: "Cannot find module 'sap/ui/qunit/utils/nextUIUpdate' or its corresponding type declarations.ts(2307)"".

**Expected behavior**
Correctly typed APIs are available.

**Workaround**
Manually place a definition file in the project:

```ts
declare module "sap/ui/qunit/utils/nextUIUpdate" {
  export default function nextUIUpdate(): Promise<void>;
}
declare module "sap/ui/qunit/utils/waitForThemeApplied" {
  export default function waitForThemeApplied(): Promise<void>;
}
```

**Additional context**
It might be worth to doublecheck the type definitions when adding the module to the distribution:
- https://github.com/SAP/openui5/blob/master/src/sap.ui.core/src/sap/ui/qunit/utils/nextUIUpdate.js looks like the parameter might not be typed as optional  (which it is)
- https://github.com/SAP/openui5/blob/master/src/sap.ui.core/src/sap/ui/qunit/utils/waitForThemeApplied.js looks like it's missing the `@public` annotation

Note that the two modules are also missing from ui5.sap.com's documentation

**Comment by codeworrior** [comment]
I'm not sure if I got your point regarding the two APIs at the end: 
* the `clock` parameter of `nextUIUpdate` is optional and documented as such and 
* `waitForThemeApplied` was never intended as a public API. Did you find references to it in our documentation?

In general, it was a conscious decision so far to not make the testing helpers (`sap/ui/qunit/**`) public. But I understand that this is at least inconsistent if we, at the same time, mention them in replacement lists.

**Comment by LukasHeimann** [comment]
- `clock` that might have been my mistake, I was not sure about the JSDoc syntax -- in TypeScript, an explicit `?` or `| undefined` would have been necessary
- `waitForThemeApplied`: in our code, we have built exactly the same with deprecated `Core` APIs. When I looked to find out about `nextUIUpdate`, didn't find anything in the docs and types, but in the code, I thought using it would also be possible (but broken typewise for the same reasons).

`applyChanges` suggests to use `nextUIUpdate` for test code -- which was exactly my use case: https://github.com/SAP/openui5/blob/b1e9f4df71716680d1fd0416c363fcd9a659133f/src/sap.ui.core/src/sap/ui/core/Core.js#L2305-L2310

I'd really like these two functions, they fill the exact spot that the test for my small custom control needs.

**Comment by akudev** [comment]
I don't think there is any issue in the dts generator, right?

The types not being marked as public in the OpenUI5 sources is nothing that can be changed in the generator. After all you explicitly wrote "the two modules are also missing from ui5.sap.com's documentation", which is not a result of this generator. As far as I see everything is about the annotations in the original UI5 code. So please open an issue in the OpenUI5 repo to get the officially recommended replacements actually usable.

**Comment by LukasHeimann** [comment]
`nextUIUpdate` is in fact marked as public, but I'm going to go ahead and also open something at OpenUI5

**Comment by akudev** [comment]
Ok, I'll check.

**Comment by codeworrior** [comment]
@akudev  As you might remember, we've excluded `sap/ui/qunit` from the docs. 

It's done here: https://github.com/SAP/openui5/blob/master/src/sap.ui.core/src/sap/ui/core/.library#L125.

**Comment by LukasHeimann** [comment]
I've opened https://github.com/SAP/openui5/issues/4074 as suggested :)

**Comment by akudev** [comment]
> @akudev As you might remember, we've excluded `sap/ui/qunit` from the docs.

Right.
More precisely: a bit more than ten years and three months ago. It feels like it was yesterday. ;-)

![image](https://github.com/SAP/ui5-typescript/assets/4866568/db5e508e-6186-452f-beef-b15e584153eb)
