### ISSUE TITLE
dts-generator generating classes with no methods

### ISSUE THREAD

**Issue by lucasheim** [SAP/ui5-typescript#46]
I'm trying to use the `dts-generator` to generate types for version 1.52.27 of SAPUI5. Definition file generation seems to be working in general, but every class ends up with no methods. I debugged the code and ended up in [this line](https://github.com/SAP/ui5-typescript/blob/78dd94c6e99f9773acec49ab37bd266d61da51a9/packages/dts-generator/lib/phases/ast-fixer.js#L55).

It seems like the `removeBadMethods` is removing every method because it's calling lodash's include with the wrong parameter order.

![image](https://user-images.githubusercontent.com/13325346/68902083-20d92c80-0716-11ea-8735-775ce155a244.png)

It should be `(collection, value)`, instead of `(value, collection)` as stated in [lodash docs](https://lodash.com/docs/#includes).

**Comment by bd82** [comment]
That is a good catch Thanks 👍 

There may be more issues hiding here because:
- How do the 1.60 classes include methods?
  - Is a different lodash version used somehow?
  - Maybe this filter never worked for other reasons?
- There may be different API.json structure for version 1.52 which will break the generation.

**Comment by lucasheim** [comment]
Did some more testing, this was probably never catched as it seems to work when `badMethods` is not an empty array, as it's the case for the script in ts-types.

**Comment by bd82** [comment]
I'll attempt to fix this, release a new vesion and regenerate the signatures for 1.60 next week.

**Comment by bd82** [comment]
Try: https://www.npmjs.com/package/@ui5/dts-generator/v/1.60.4
