### ISSUE TITLE
Inconsistent phrasing in @deprecated / @experimental tags

### ISSUE THREAD

**Issue by matz3** [SAP/ui5-typescript#468]
**Describe the bug**

Deprecated APIs are described differently in the TypeScript definitions and the UI5 SDK API Reference.

In TypeScript it is e.g. `@deprecated — (since 1.118) - Please use sap.ui.core.Core.ready Core.ready instead.` while in the [UI5 SDK](https://ui5.sap.com/#/api/sap.ui.core.Core%23methods/attachInit) it is `Deprecated as of version 1.118. Please use [Core.ready](https://ui5.sap.com/#api/sap.ui.core.Core%23methods/ready) instead.`.

AFAICS this also applies to `@experimental`.

**Expected behavior**

Both descriptions should use the same phrasing. According to https://github.com/SAP/openui5/blob/master/docs/guidelines/jsdoc.md `As of version X.Y.Z` should be used.

**Additional context**

I can file a PR if this change would be accepted.

**Comment by akudev** [comment]
I guess it makes sense and a PR is welcome.
