### ISSUE TITLE
How to get dependencies from a library?

### ISSUE THREAD

**Issue by lucasheim** [SAP/ui5-typescript#47]
I was creating a generation script based on [this example on ts-types](https://github.com/SAP/ui5-typescript/blob/master/packages/ts-types/scripts/gen-dts.js), but I didn't understand how to get the dependencies for each library. The OpenUI5 ones are hardcoded in the file, but how did you get this information? Do you have a script that extracts this from the `api.json` files?

![image](https://user-images.githubusercontent.com/13325346/69053008-3638aa00-09e7-11ea-99fd-58f7003caead.png)

**Comment by bd82** [comment]
I think I **manually** constructed this data looking at the dependencies of the OpenUI5 libraries package.json dependencies e.g:
- https://www.npmjs.com/package/@openui5/sap.ui.dt/v/1.60.21?activeTab=dependencies

This is not the best approach (manual) and it could be automated, however I hope that
the generation of signatures would (at some point in the future) be part of OpenUI5
build/release artifacts and not a concern of this repo, so this manual approach is sufficient for now.

In what context / purpose are you working on generating signatures?

**Comment by lucasheim** [comment]
We currently use typescript with SAP UI5 projects we develop, but we have our own dts generator, and I'm trying to eliminate all of our custom tools in favor of SAP or open source ones.

**Comment by bd82** [comment]
> We currently use typescript with SAP UI5 projects we develop, but we have our own dts generator, and I'm trying to eliminate all of our custom tools in favor of SAP or open source ones.

Sounds great 😄 

You can also contact me "internally" to discuss this my SAP email address git be found in the git commit history.
