### ISSUE TITLE
URLHelper missing in sap.m types

### ISSUE THREAD

**Issue by BenReim** [SAP/ui5-typescript#51]
```javascript
sap.m.URLHelper.redirect(sUrl)
```

When using the `URLHelper`, which exists as a global on the `sap.m` library, typescript shows an error message:
```
Property 'URLHelper' does not exist on type 'typeof m'.
```

**Comment by bd82** [comment]
Looks like it is being automatically converted to an interface and not treated as a namespace, this is probably done as URLHelper is used as a type name somewhere
and a namespace in TypeScript cannot be used as a Type.

- https://github.com/SAP/ui5-typescript/blob/be34da9da8f3cc631d41cdd00d348e312abcbb43/packages/ts-types/scripts/directives/namespaces-to-interfaces.js#L4

Maybe this is should be solved similarly to #48 where **multiple** TypeScript artifacts
should be generated from a single api.json entity.

**Comment by bd82** [comment]
Need to consult on this with UI5 Colleagues, basically is this API considered legacy or modern? Does it have a module alternative (instead of globals?)

**Comment by bd82** [comment]
This was fixed in #208 
and will be released in the next version of the dts-generator.

However the `directives` passed to the DTS-generator in the UI5 build will also have to be adjusted.
- https://github.com/SAP/ui5-typescript/pull/208/files#diff-03cedc85309eb37b05bfb3335f5a362c93766cd5629e09ce05cbef9b30891f5fR1-R6

**Comment by bd82** [comment]
@petermuessig @codeworrior @RandomByte **FYI**

**Comment by HappyHepo** [comment]
This seems to be an issue again as of 1.115 as the previous way of
```typescript
import { URLHelper } from "sap/m/library";
URLHelper.redirect(...);
```

does not work anymore, as URLHelper is not exported in `sap/m/library` anymore and `does not exist on typeof m`.
Missing line in the .d.ts:
```typescript
export const URLHelper: URLHelper;
```

**Comment by akudev** [comment]
Thanks for reporting. Seems like fallout of the recent bigger changes.

**Comment by petermuessig** [comment]
Seems that the URLHelper isn't exported anymore. I'll have to check...

**Comment by petermuessig** [comment]
@akudev: it is as @HappyHepo describes - just `export interface` doesn't work, the following line needs to be added after the interface has been defined: `export const URLHelper: URLHelper;` - otherwise is cannot be used as a type!

**Comment by akudev** [comment]
@petermuessig As value, you mean, but yes. Both are needed, as in 1.114 and before.

**Comment by petermuessig** [comment]
Issue has been found an will be addressed with the next release of the types. Not sure yet, whether we have it as part of 1.115.1 or 1.116.0

**Comment by petermuessig** [comment]
@akudev : `export interface` is wrong as it produces an error!

![image](https://github.com/SAP/ui5-typescript/assets/1589419/b53e490f-0fe4-4b17-96f5-a0fdcc171fab)

the interface must not be exported but the const value!

**Comment by akudev** [comment]
Also with the ts-types ("globals"), the bug is fixed in the meantime. Closing.

![image](https://github.com/SAP/ui5-typescript/assets/4866568/e61bd620-ff13-483e-abb6-1eb2c799587a)
