### ISSUE TITLE
Types missing for some borrowed methods

### ISSUE THREAD

**Issue by BenReim** [SAP/ui5-typescript#52]
As an example, `getPath` should be available as a member method of [ODataListBinding](https://openui5nightly.hana.ondemand.com/api/sap.ui.model.odata.v2.ODataListBinding#methods/Summary), since it is being inherited `sap.ui.model.Binding`

However, typescript raises the following error:
```Property 'getPath' does not exist on type 'ODataListBinding'.```

**Comment by bd82** [comment]
I do not see any getPath in version 1.60
- https://sapui5.hana.ondemand.com/1.60.20/#/api/sap.ui.model.odata.v2.ODataListBinding/methods/Summary

Currently only version 1.60 of the signatures are provided while we wait (hopefully)
for integration into the OpenUI5 build process.

- https://github.com/SAP/ui5-typescript/issues/38#issuecomment-512542365

**Comment by BenReim** [comment]
Thanks for clarifying! I will therefore close this issue.
