### ISSUE TITLE
Planned release date

### ISSUE THREAD

**Issue by EdStrickland** [SAP/ui5-typescript#96]
Hi team,
I understand that this is a beta project but is it planned to release in the near future? Or is there a roadmap that I can refer to?

**Comment by htammen** [comment]
I don't know about the concrete roadmap but they are working on it. See this video (mostly near the end) https://www.youtube.com/watch?v=v6ImEbZRRlg&list=PLpQebylHrdh5XQts8bKoMUKexpun_YPvU&index=1

**Comment by bd82** [comment]
Hello @EdStrickland 

There has been progress in this topic although this **is still beta/experimental.**
See the @sapui5/ts-types package which contains signatures for newer versions of UI5 (OpenUI5 + Dist Layer).
- https://www.npmjs.com/package/@sapui5/ts-types

However these signatures are not prefect yet as they still include some errors...

**Comment by bd82** [comment]
Closing this as I think it was answered to the best of our knowledge.
